### ISSUE TITLE
Ajout des commandes dockers pour Docker Desktop for Windows

### ISSUE THREAD

**Issue by ghost** [haxom/simics#1]
Eolienne/README_docker.md
===================
ou, sous Windows :
```
C:\> for /f "delims=" %i in ('docker run --publish <local port>:80 --rm --detach simics_eolienne') do set DOCKER_ID=%i
C:\> docker inspect --format='{{.NetworkSettings.IPAddress}}' %DOCKER_ID%
```

UsineEol/README_docker.md
===================
ou, sous Windows :
```
C:\> set EOL_IP=<IP Eolienne 1>;<IP Eolienne 2>;IP Eolienne 3>…
C:\> for /f "delims=" %i in ('docker run --rm -e "EOL_IP=%EOL_IP%" -p 80:80 --detach) do set DOCKER_ID=%i
C:\> docker inspect --format='{{.NetworkSettings.IPAddress}}' %DOCKER_ID%
```

**Comment by haxom** [comment]
Merci pour les commandes @Cyrtiac.

Je vais intégrer ces commandes. A noter quand même que maintenant, Docker Desktop for Windows s'intègre avec WSL2.  
Les dockers peuvent donc être construits depuis WSL2 (Ubuntu) et sont accessibles sur le Docker Windows o/
